# https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/getting-started/
# https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/configuration/

camunda:
  client:
    mode: saas
    auth:
      client-id: <my-client>
      client-secret: <my-client>
    cloud:
      cluster-id: 91fd88d1-c1f1-4092-9331-e1cc74260efa
      region: jfk-1
